### ISSUE TITLE
[Bug]: Failed to load character avatar 

### ISSUE THREAD

**Issue by tbergmueller** [mml-io/3d-web-experience#114]
### Describe the bug

When deploying the 3d-web-experience to a Web-Server with public IP (and/or Caddy reverse proxy, same behavior with and without proxy, with and without https), the Mesh of the Avatars is not loaded. Note that the avatars are labelled and also collisions work. 

**Observed behavior**
On non-localhost (see https://hackverse.quintinius.xyz), the avatars cannot be loaded. Note that external GLB via `<v-model>`load fine, refer this [MML Document](https://github.com/tbergmueller/mml-hackground/blob/main/example/server/mml-documents/example-mml.html#L2)
![image](https://github.com/mml-io/3d-web-experience/assets/2257335/02f07ebe-211b-4319-ad7b-d662c160c4e3)

Error from client-side console, Google Chrome and Firefox have identical behavior:
![image](https://github.com/mml-io/3d-web-experience/assets/2257335/7d46d0d1-2646-46f4-af2e-a2746a67730b)

Obviously, the (cached) GLTF/GLB cannot be delivered to the client. I did not see any CORS warnings or similar. When trying to access the URL, i.e. `https://hackverse.quintinius.xyz/3967a9d6-ce92-4ab5-8764-39be57a6d6ec`, HTTP 404 is returned, the bodyreads as `Cannot GET /3967a9d6-ce92-4ab5-8764-39be57a6d6ec`

### Expected behavior

The avatar is loaded and rendered. This works on localhost (same behavior when accessing it via local network):
![image](https://github.com/mml-io/3d-web-experience/assets/2257335/c438aca1-a1f0-477e-ba28-f490ea002535)

### How to reproduce the bug

`git clone https://github.com/tbergmueller/mml-hackground/`
(this is corresponds to this repository's https://github.com/mml-io/3d-web-experience/commit/6a3b4e06c3bb840ba87928c872be7deb50b19257, it's only extended by a docker-compose and some models in the mml-file) 

```
npm install
npm run iterate
```

OR via my dockerized environment from [this commit](https://github.com/mml-io/3d-web-experience/commit/c2f24f4df1f90e93c49606b8e61bc5fee1c074d4)
```
docker compose build --no-cache
docker compose up -d
```

You can play the deployed version on 
https://hackverse.quintinius.xyz.

### Link to the code that reproduces this bug

git clone https://github.com/tbergmueller/mml-hackground/

### Extra details

I tried to deploy on multiple servers, it is currently deployed on a dedicated root server https://www.hetzner.com/de/dedicated-rootserver/ running reverse-proxy via https://caddyserver.com/ 

The observed behavior is the same across different servers and whether using HTTP, HTTPS, reverse-proxy or not.

**Comment by tbergmueller** [comment]
I'm happy to investigate further and contribute a bugfix, just wanted to check with @MarcusLongmuir before if it is a stupid configuration error on my side or indeed a bug

**Comment by MarcusLongmuir** [comment]
Hey @tbergmueller. It looks like the assets being used for the avatars (e.g. `https://hackverse.quintinius.xyz/95b63e90-d72b-4732-8ef7-363997a84f65`) aren't being served correctly and from a response I can see it looks like they're pointing at Git LFS references that haven't been downloaded. 

Is it possible the server you're hosting from has cloned the repo, but doesn't have Git LFS installed?

**Comment by tbergmueller** [comment]
Thank you, that's precisely the reason - confirm it's working now, after cloning with git-lfs installed.

Closing this. Let me know in case you want me to contribute the docker-compose setup [would do it cleaner then of course ;)]
